module.exports.userData = [
  {twitter_id: '12345',
    username: 'WineMuse',
    twitter_url: 'https://twitter.com/WineMuse',
    fullname: 'Emily Crichton',
    location: 'San Francisco',
    profile_img: 'https://pbs.twimg.com/profile_images/2562772913/nj2vxvwe213bidsvj4n1_400x400.jpeg',
    about_me: 'Muse for hire. Excels in tomfoolery & higher than average wine consumption. Co-founder @oenomad',
    matches: [],
    following: ['09876'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: ['13579']},
  {twitter_id: '67890',
    username: 'VinumFerus',
    twitter_url: 'https://twitter.com/VinumFerus',
    fullname: 'Natalie Bowman Lee',
    location: 'McMinnville, OR',
    profile_img: 'https://pbs.twimg.com/profile_images/839304322089246721/5qZt4Er1_400x400.jpg',
    about_me: 'Glamorous winemaker producing killer Pinot Noir of all shades in Oregon\'s Willamette Valley. Lots of foot stompin\'. Certified Somm.',
    matches: [],
    following: ['09876', '12405'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: []},
  {twitter_id: '09876',
    username: 'Oenomad',
    twitter_url: 'https://twitter.com/oenomad',
    fullname: 'Oenomad',
    location: 'San Francisco, CA',
    profile_img: 'https://pbs.twimg.com/profile_images/667081548672299008/3VIEIthQ_400x400.png',
    about_me: 'Never Wing It In Wine Country Again.',
    matches: [],
    following: ['13579'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: []},
  {twitter_id: '54321',
    username: 'JamieGall1930',
    twitter_url: 'https://twitter.com/JamieGall1930',
    fullname: 'Jamie',
    location: 'Sonoma, CA',
    profile_img: 'https://pbs.twimg.com/profile_images/494657526961434625/edF38vlw_400x400.jpeg',
    about_me: 'A Born and Raised Minnesota Girl who has landed herself in Wine Country. Blogger of All Things Wine, Travel, Food and HER. Photo by Tina Case Photography.',
    matches: [],
    following: ['09876'],
    friends: ['13579'],
    blocked: ['12345'],
    pending_approval: [],
    pending_request: ['24680']},
  {twitter_id: '13579',
    username: 'chrisbharrison',
    twitter_url: 'https://twitter.com/chrisbharrison',
    fullname: 'Chris Harrison',
    location: 'Los Angeles',
    profile_img: 'https://pbs.twimg.com/profile_images/378800000101833847/1d2b68f0f8149b6bf4023f89aac9e507_400x400.jpeg',
    about_me: 'Host, Bachelor, Miss America, Millionaire and pretty much all things involving cash, crying, roses, crowns & relationships! Author The Perfect Letter',
    matches: [],
    following: ['09876', '12405'],
    friends: ['54321', '24680'],
    blocked: [],
    pending_approval: ['12345'],
    pending_request: []},
  {twitter_id: '24680',
    username: 'CorinneOly',
    twitter_url: 'https://twitter.com/CorinneOly',
    fullname: 'Corinne olympios',
    profile_img: 'https://pbs.twimg.com/profile_images/795698272262377472/lK9J59o1_400x400.jpg',
    about_me: 'Bachelor 21 • insta- Colympios • Corninquiries@gmail.com',
    matches: ['09876', '12345'],
    following: [],
    friends: ['13579'],
    blocked: [],
    pending_approval: ['54321'],
    pending_request: []}
];

module.exports.messageData = [
  {sender: 'CorinneOly',
    receiver: 'chrisbharrison',
    message: 'Hey Girl! What\'s up?'},
  {sender: 'chrisbharrison',
    receiver: 'CorinneOly',
    message: 'Yo! Am I getting that rose tonight or what??'},
  {sender: 'CorinneOly',
    receiver: 'chrisbharrison',
    message: 'Haha...we will see...'},
];

module.exports.sessionData = [
  {hash: 'testSession_asdfghtarefsdlkjha8oourqoijefalkm'},
  {hash: '2222Session_asdfghtarefsdlkjha8oourqoijefalkm'},
  {hash: '3333Session_asdfghtarefsdlkjha8oourqoijefalkm'}
];

// { "_id" : ObjectId("599f85d8686c54f7ea11ee34"), "twitter_id" : "772236185745842176", "username" : "martinkchang", "twitter_url" : null, "fullname" : "Martin Chang", "location" : "", "profile_img" : "http://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8c3bd184bff94ede73e2"), "twitter_id" : "900902726355136512", "username" : "80hungryhippos", "twitter_url" : null, "fullname" : "Hungry Hippos", "location" : "", "profile_img" : "http://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8d07d184bff94ede73e3"), "twitter_id" : "900906184147845120", "username" : "kettch22", "twitter_url" : null, "fullname" : "k22", "location" : "", "profile_img" : "http://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8e18d184bff94ede73e4"), "twitter_id" : "747826521725763584", "username" : "Bird_Mantis", "twitter_url" : "https://t.co/Fx4RsZgeeD", "fullname" : "BIRDMANTIS", "location" : "Los Angeles, CA", "profile_img" : "http://pbs.twimg.com/profile_images/748026330017587200/BKWarxpm_400x400.jpg", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8e48d184bff94ede73e5"), "twitter_id" : "893651977338368000", "username" : "realcodebreaker", "twitter_url" : null, "fullname" : "Cody Unger", "location" : "", "profile_img" : "http://pbs.twimg.com/profile_images/900905051996147712/DtgtjN_t_400x400.jpg", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8e83d184bff94ede73e6"), "twitter_id" : "900906961348186112", "username" : "jasperthecow", "twitter_url" : null, "fullname" : "Jasper Cow", "location" : "", "profile_img" : "http://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png", "about_me" : "", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8f70d184bff94ede73e7"), "twitter_id" : "231326973", "username" : "whithang", "twitter_url" : "https://t.co/PUFsknDDa3", "fullname" : "Kelly Whiting", "location" : "San Francisco, CA", "profile_img" : "http://pbs.twimg.com/profile_images/669421714204450817/fN8Xte0M_400x400.jpg", "about_me" : "wine tech entrepreneur | check out https://t.co/RCc7KXeXJ8 for a free planning tool if you are going wine tasting in California", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }
// { "_id" : ObjectId("599f8fb3d184bff94ede73e8"), "twitter_id" : "4221402799", "username" : "oenomad", "twitter_url" : "https://t.co/PUFsknDDa3", "fullname" : "Oenomad", "location" : "San Francisco, CA", "profile_img" : "http://pbs.twimg.com/profile_images/667081548672299008/3VIEIthQ_400x400.png", "about_me" : "Never Wing It In Wine Country Again.", "pending_request" : [ ], "pending_approval" : [ ], "blocked" : [ ], "friends" : [ ], "following" : [ ], "matches" : [ ], "__v" : 0 }