module.exports.userData = [
  {twitter_id: '12345',
    username: 'WineMuse',
    twitter_url: 'https://twitter.com/WineMuse',
    fullname: 'Emily Crichton',
    location: 'San Francisco',
    profile_img: 'https://pbs.twimg.com/profile_images/2562772913/nj2vxvwe213bidsvj4n1_400x400.jpeg',
    about_me: 'Muse for hire. Excels in tomfoolery & higher than average wine consumption. Co-founder @oenomad',
    matches: [],
    following: ['09876'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: ['13579']},
  {twitter_id: '67890',
    username: 'VinumFerus',
    twitter_url: 'https://twitter.com/VinumFerus',
    fullname: 'Natalie Bowman Lee',
    location: 'McMinnville, OR',
    profile_img: 'https://pbs.twimg.com/profile_images/839304322089246721/5qZt4Er1_400x400.jpg',
    about_me: 'Glamorous winemaker producing killer Pinot Noir of all shades in Oregon\'s Willamette Valley. Lots of foot stompin\'. Certified Somm.',
    matches: [],
    following: ['09876'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: []},
  {twitter_id: '09876',
    username: 'Oenomad',
    twitter_url: 'https://twitter.com/oenomad',
    fullname: 'Oenomad',
    location: 'San Francisco, CA',
    profile_img: 'https://pbs.twimg.com/profile_images/667081548672299008/3VIEIthQ_400x400.png',
    about_me: 'Never Wing It In Wine Country Again.',
    matches: [],
    following: ['13579'],
    friends: [],
    blocked: [],
    pending_approval: [],
    pending_request: []},
  {twitter_id: '54321',
    username: 'JamieGall1930',
    twitter_url: 'https://twitter.com/JamieGall1930',
    fullname: 'Jamie',
    location: 'Sonoma, CA',
    profile_img: 'https://pbs.twimg.com/profile_images/494657526961434625/edF38vlw_400x400.jpeg',
    about_me: 'A Born and Raised Minnesota Girl who has landed herself in Wine Country. Blogger of All Things Wine, Travel, Food and HER. Photo by Tina Case Photography.',
    matches: [],
    following: ['09876'],
    friends: ['13579'],
    blocked: ['12345'],
    pending_approval: [],
    pending_request: ['24680']},
  {twitter_id: '13579',
    username: 'chrisbharrison',
    twitter_url: 'https://twitter.com/chrisbharrison',
    fullname: 'Chris Harrison',
    location: 'Los Angeles',
    profile_img: 'https://pbs.twimg.com/profile_images/378800000101833847/1d2b68f0f8149b6bf4023f89aac9e507_400x400.jpeg',
    about_me: 'Host, Bachelor, Miss America, Millionaire and pretty much all things involving cash, crying, roses, crowns & relationships! Author The Perfect Letter',
    matches: [],
    following: [],
    friends: ['54321', '24680'],
    blocked: [],
    pending_approval: ['12345'],
    pending_request: []},
  {twitter_id: '24680',
    username: 'CorinneOly',
    twitter_url: 'https://twitter.com/CorinneOly',
    fullname: 'Corinne olympios',
    profile_img: 'https://pbs.twimg.com/profile_images/795698272262377472/lK9J59o1_400x400.jpg',
    about_me: 'Bachelor 21 • insta- Colympios • Corninquiries@gmail.com',
    matches: ['09876', '12345'],
    following: [],
    friends: ['13579'],
    blocked: [],
    pending_approval: ['54321'],
    pending_request: []}
];

module.exports.messageData = [
  {sender: 'CorinneOly',
    receiver: 'chrisbharrison',
    message: 'Hey Girl! What\'s up?'},
  {sender: 'chrisbharrison',
    receiver: 'CorinneOly',
    message: 'Yo! Am I getting that rose tonight or what??'},
  {sender: 'CorinneOly',
    receiver: 'chrisbharrison',
    message: 'Haha...we will see...'},
];

module.exports.sessionData = [
  {hash: 'testSession_asdfghtarefsdlkjha8oourqoijefalkm'},
  {hash: '2222Session_asdfghtarefsdlkjha8oourqoijefalkm'},
  {hash: '3333Session_asdfghtarefsdlkjha8oourqoijefalkm'}
];
